name: ascat_env
channels:
  - jmcmurray
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - asn1crypto=1.3.0=py36_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py36_0
  - blas=1.0=openblas
  - bleach=3.1.4=py_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cartopy=0.17.0=py36hbb7e04d_1
  - certifi=2020.4.5.1=py36_0
  - cffi=1.14.0=py36h2e261b9_0
  - cftime=1.1.1.2=py36h035aef0_0
  - chardet=3.0.4=py36_1003
  - cryptography=2.8=py36h1ba5d50_0
  - curl=7.69.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - cython=0.29.17=py36h831f99a_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - eccodes=2.17.0=h59f7be3_1
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - geos=3.7.1=he6710b0_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=nompi_py36h513d04c_102
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py36_0
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jasper=1.900.1=hd497a04_4
  - jedi=0.17.0=py36_0
  - jinja2=2.11.2=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py36_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.17.1=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libaec=1.0.4=he1b5a44_1
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=16_openblas
  - libnetcdf=4.7.4=nompi_h9f9fd6a_101
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - lxml=4.5.0=py36hefd8a0e_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mistune=0.8.4=py36h7b6447c_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.6=py_0
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.5.3=nompi_py36h90ce072_103
  - notebook=6.0.3=py36_0
  - numpy=1.18.1=py36h7314795_1
  - olefile=0.46=py36_0
  - openssl=1.1.1g=h7b6447c_0
  - os=0.1.4=0
  - owslib=0.17.0=py36_0
  - pandas=1.0.3=py36h830a2c2_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.7.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=20.0.2=py_2
  - proj4=5.2.0=he6710b0_1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py36_0
  - pybufr-ecmwf=0.82=py36_1
  - pycparser=2.20=py_0
  - pyepsg=0.4.0=py36_0
  - pygments=2.6.1=py_0
  - pygrib=2.0.4=py36h55c65ac_0
  - pykdtree=1.3.1=py36hdd07704_2
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyproj=1.9.6=py36h14380d9_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.16.0=py36h7b6447c_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h8356626_1011_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.3=py_0
  - qtpy=1.9.0=py_0
  - qutil=3.2.1=6
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py36_0
  - scipy=1.4.1=py36habc2bb6_0
  - send2trash=1.5.0=py36_0
  - setuptools=46.1.3=py36_0
  - shapely=1.6.4=py36h86c5351_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py36h7b6447c_1
  - traitlets=4.3.3=py36_0
  - urllib3=1.25.8=py36_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - ascat==1.0.2
    - configobj==5.0.6
    - configparser==5.0.0
    - ismn==0.3.2
    - more-itertools==8.2.0
    - pipdeptree==0.13.2
    - pygeobase==0.3.18
    - pygeogrids==0.2.6
    - pynetcf==0.2.1
    - pyresample==1.15.0
    - pytesmo==0.8
    - pyyaml==5.3.1
    - repurpose==0.7.1
prefix: /home/ninadel/anaconda3/envs/ascat_env

