name: sm_win
channels:
  - jmcmurray
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py36_0
  - basemap=1.2.0=py36h4e5d7af_0
  - basemap-data-hires=1.2.0=0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.1.1=0
  - cartopy=0.16.0=py36hc59b559_0
  - certifi=2020.4.5.1=py36_0
  - cffi=1.14.0=py36h7a1dbc1_0
  - cftime=1.1.2=py36h2a96729_0
  - chardet=3.0.4=py36_1003
  - colorama=0.4.3=py_0
  - cryptography=2.9.2=py36h7a1dbc1_0
  - curl=7.69.1=h2a8f88b_0
  - cycler=0.10.0=py36h009560c_0
  - cython=0.29.17=py36ha925a31_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - eccodes=2.17.0=hd0e664e_1
  - entrypoints=0.3=py36_0
  - freetype=2.9.1=ha9979f8_1
  - geos=3.6.2=h9ef7328_2
  - h5py=2.10.0=nompi_py36h422b98e_102
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.5=nompi_ha405e13_1104
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py36_0
  - jinja2=2.11.2=py_0
  - jpeg=9c=hfa6e2cd_1001
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py36_0
  - kiwisolver=1.2.0=py36h74a9793_0
  - krb5=1.17.1=hc04afaa_0
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libcurl=7.69.1=h2a8f88b_0
  - libiconv=1.15=h1df5818_7
  - liblapack=3.8.0=15_mkl
  - libnetcdf=4.7.4=nompi_hc957ea6_101
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.9=h464c3ec_0
  - libxslt=1.1.33=h579f668_0
  - lxml=4.5.0=py36h1350720_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36he774522_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36h64f37c6_0
  - mistune=0.8.4=py36he774522_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py36hb782905_0
  - mkl_fft=1.0.15=py36h14836fe_0
  - mkl_random=1.1.0=py36h675688f_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.6=py_0
  - netcdf4=1.5.3=nompi_py36h86f0940_103
  - notebook=6.0.3=py36_0
  - numpy=1.18.4=py36h4d86e3b_0
  - numpy-base=1.18.1=py36hc3f5095_1
  - olefile=0.46=py36_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1g=he774522_0
  - os=0.1.4=0
  - owslib=0.18.0=py_0
  - pandas=1.0.3=py36hcc50265_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.1.2=py36hcc1f983_0
  - pip=20.0.2=py36_3
  - proj4=5.1.0=hfa6e2cd_1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - pycparser=2.20=py_0
  - pyepsg=0.4.0=py36_0
  - pygments=2.6.1=py_0
  - pygrib=2.0.4=py36hbc73418_0
  - pykdtree=1.3.1=py36h8c2d366_2
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.7=py_0
  - pyproj=1.9.5.1=py36hb98d9bb_1
  - pyqt=5.9.2=py36h6538335_2
  - pyreadline=2.1=py36_1
  - pyresample=1.15.0=py36h5076640_0
  - pyrsistent=0.16.0=py36he774522_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h9f7ef89_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=py_0
  - pywin32=227=py36he774522_1
  - pywinpty=0.5.7=py36_0
  - pyzmq=18.1.1=py36ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.7.3=py_0
  - qtpy=1.9.0=py_0
  - qutil=3.2.1=6
  - requests=2.23.0=py36_0
  - scipy=1.4.1=py36h9439919_0
  - send2trash=1.5.0=py36_0
  - setuptools=46.1.3=py36_0
  - shapely=1.6.4=py36hc90234e_0
  - sip=4.19.8=py36h6538335_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=h2a8f88b_1
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.4=py36he774522_1
  - traitlets=4.3.3=py36_0
  - urllib3=1.25.8=py36_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.3.1=h33f27b4_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.3.7=h508b16e_0
  - pip:
    - ascat==1.0.2
    - configobj==5.0.6
    - configparser==5.0.0
    - datedown==0.3
    - ease-grid==0.1
    - gldas==0.5
    - ismn==0.3.2
    - more-itertools==8.2.0
    - pygeobase==0.3.18
    - pygeogrids==0.2.6
    - pynetcf==0.2.2
    - pytesmo==0.8
    - pyyaml==5.3.1
    - repurpose==0.7.1
    - smap-io==0.3
    - trollsift==0.2.1
prefix: C:\ProgramData\Anaconda3\envs\sm_win

